name: "Apply Stack after PR is Merged"

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  terraform:
    name: "Terraform CDK Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      # Remove this step if you don't have any
#      - name: Run unit tests
#        run: yarn test

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v3
        with:
          cdktfVersion: 0.20.4
          terraformVersion: 1.7.4
          mode: auto-approve-apply
          stackName: aws_instance
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}